# Generated by Django 4.0.6 on 2022-07-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('address', models.TextField(max_length=200, verbose_name='Адресс организации')),
                ('fraud_weight', models.IntegerField(verbose_name='Уровень жульничества')),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.IntegerField(verbose_name='Номер счета')),
                ('check_sum', models.IntegerField(verbose_name='Сумма счета')),
                ('date', models.DateTimeField(verbose_name='Дата счета')),
                ('service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('fraud_score', models.IntegerField(verbose_name='Оценка мошенничества')),
                ('service_class', models.IntegerField(verbose_name='Класс услуги')),
                ('service_name', models.CharField(max_length=200, verbose_name='Наименование класса услуги')),
                ('client_org', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.organization', verbose_name='Название организации')),
                ('clinet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.client')),
            ],
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'client_name'), name='unique_org_name_client_name'),
        ),
        migrations.AddConstraint(
            model_name='bills',
            constraint=models.UniqueConstraint(fields=('client_org', 'check_number'), name='unique_org_check_number'),
        ),
    ]
